### ISSUE TITLE
cmake is not work in cygwin, although in linux sometime.  raise error with "Could not find CMAKE_ROOT !!!"

### ISSUE THREAD

**Issue by heresy256** [piscisaureus/wepoll#11]
May you generate a simple makefile for work?

**Comment by piscisaureus** [comment]
I'm sorry but it's not clear what the issue is. I'd suggest you read the readme and use the 'dist' branch (https://github.com/piscisaureus/wepoll/tree/dist) as suggested.

Cygwin is not supported as a platform; I suspect it could be made to work with some modifications.
I am out of my depth why you'd want to compile it on linux; obviously that will never work.
