### ISSUE TITLE
wepoll-combined.dll build fails is VC15 2017

### ISSUE THREAD

**Issue by RussellHaley** [piscisaureus/wepoll#7]
Hi, 

I generated a solution file using cmake and all the targets except wepoll-combined.dll build. 

Project "C:\Users\russh\git\wepoll\build\wepoll-combined.dll.vcxproj.metaproj" (23) is building "C:\Users\russh\git\wepoll\build\wepoll-combined.dll.vcxproj" (24) on
 node 1 (default targets).
InitializeBuildStatus:
  Touching "wepoll-combined.dll.dir\Debug\wepoll-c.D6E8EA87.tlog\unsuccessfulbuild".
CustomBuild:
  Building Custom Rule C:/Users/russh/Git/wepoll/CMakeLists.txt
  CMake does not need to re-run because C:/Users/russh/Git/wepoll/build/CMakeFiles/generate.stamp is up-to-date.
  Generating dist/wepoll.c
  'node' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code
9009. [C:\Users\russh\git\wepoll\build\wepoll-combined.dll.vcxproj]
Done Building Project "C:\Users\russh\git\wepoll\build\wepoll-combined.dll.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\russh\git\wepoll\build\wepoll-combined.dll.vcxproj.metaproj" (default targets) -- FAILED.

Let me know if you want more details (build steps, full output etc). I'll move forward with the other modules for now I guess? I look forward to trying out wepoll. Thanks!
Russ

**Comment by piscisaureus** [comment]
@RussellHaley 

I suppose you want to use wepoll as part of some bigger project, I would recommend you just grab wepoll.h and wepoll.c from the dist branch (https://github.com/piscisaureus/wepoll/tree/dist) and add them to your project.

But since you ask - to build wepoll-combined.dll you need to install a recent-ish version of node.js and have it available on your PATH. That's also the case for the test-all target btw.

**Comment by RussellHaley** [comment]
Great, that's what I needed to know. Thanks for the feedback!
